### ISSUE TITLE
Unable to generate params.hpp due to SAGE error

### ISSUE THREAD

**Issue by meyira** [isogeny-scallop/scallop#1]
Hi, 
I just wanted to try the code and upon running `make` the sage script that should generate params.h produces the following output: 

```
#pragma once

#include "bigint.hpp"

Traceback (most recent call last):
  File "scallop/params.sage.py", line 231, in <module>
    print(f'constexpr int_t<{sz(ALPHA1):3}> ALPHA1 = {ALPHA1:+#x}_cppi;')
  File "scallop/params.sage.py", line 223, in <lambda>
    sz = lambda t: t.bit_length()//_sage_const_64 *_sage_const_64  + _sage_const_64 
  File "sage/structure/element.pyx", line 494, in sage.structure.element.Element.__getattr__ (build/cythonized/sage/structure/element.c:4827)
  File "sage/structure/element.pyx", line 507, in sage.structure.element.Element.getattr_from_category (build/cythonized/sage/structure/element.c:4939)
  File "sage/cpython/getattr.pyx", line 361, in sage.cpython.getattr.getattr_from_other_class (build/cythonized/sage/cpython/getattr.c:2703)
AttributeError: 'sage.rings.integer.Integer' object has no attribute 'bit_length'

```

Could you please fix the issue/ propose a solution? I just wanted to test something, so a valid params.hpp would also be appreciated :smile:

**Comment by yyyyx4** [comment]
This error is about a method that was introduced in Sage version 9.7, released almost a year ago. Would it be an option for you to update your Sage installation to a recent version?

For your convenience, though, here's `params.hpp` for the smaller parameter set: https://pastebin.com/raw/7V9mz4kc

**Comment by meyira** [comment]
Thank you! Maybe piggybacking off this thread: there seem to be some issues with the templates when running `make` .  

Using g++: 
``` 
In file included from fp.hpp:10,
                 from params.hpp:18,
                 from main.cpp:9:
skylake.hpp: In function ‘consteval std::array<long unsigned int, 9> _1()’:
skylake.hpp:72:17: error: no matching function for call to ‘_chop(boost::multiprecision::number<boost::multiprecision::backends::cpp_int_backend<576, 576, boost::multiprecision::unsigned_magnitude, boost::multiprecision::unchecked, void>, boost::multiprecision::et_off>&)’
   72 |     return _chop(v);
      |            ~~~~~^~~
skylake.hpp:61:38: note: candidate: ‘template<long unsigned int N> constexpr std::array<long unsigned int, 9> _chop(uint_t<N>&)’
   61 | constexpr std::array<uint64_t,LIMBS> _chop(uint_t<N> const &v)
      |                                      ^~~~~
skylake.hpp:61:38: note:   template argument deduction/substitution failed:
skylake.hpp:72:17: note:   mismatched types ‘long unsigned int’ and ‘unsigned int’
   72 |     return _chop(v);
      |            ~~~~~^~~
skylake.hpp: In function ‘consteval std::array<long unsigned int, 9> _R()’:
skylake.hpp:78:17: error: no matching function for call to ‘_chop(boost::multiprecision::number<boost::multiprecision::backends::cpp_int_backend<576, 576, boost::multiprecision::unsigned_magnitude, boost::multiprecision::unchecked, void>, boost::multiprecision::et_off>&)’
   78 |     return _chop(v);
      |            ~~~~~^~~
skylake.hpp:61:38: note: candidate: ‘template<long unsigned int N> constexpr std::array<long unsigned int, 9> _chop(uint_t<N>&)’
   61 | constexpr std::array<uint64_t,LIMBS> _chop(uint_t<N> const &v)
      |                                      ^~~~~
skylake.hpp:61:38: note:   template argument deduction/substitution failed:
skylake.hpp:78:17: note:   mismatched types ‘long unsigned int’ and ‘unsigned int’
   78 |     return _chop(v);
      |            ~~~~~^~~
skylake.hpp: At global scope:
skylake.hpp:81:51: error: no matching function for call to ‘_chop(uint_t<576>&)’
   81 | constexpr std::array<uint64_t,LIMBS> the_p = _chop(p);
      |                                              ~~~~~^~~
skylake.hpp:61:38: note: candidate: ‘template<long unsigned int N> constexpr std::array<long unsigned int, 9> _chop(uint_t<N>&)’
   61 | constexpr std::array<uint64_t,LIMBS> _chop(uint_t<N> const &v)
      |                                      ^~~~~
skylake.hpp:61:38: note:   template argument deduction/substitution failed:
skylake.hpp:81:51: note:   mismatched types ‘long unsigned int’ and ‘unsigned int’
   81 | constexpr std::array<uint64_t,LIMBS> the_p = _chop(p);
      |                                              ~~~~~^~~
skylake.hpp:82:48:   in ‘constexpr’ expansion of ‘_1()’
skylake.hpp:82:48: error: ‘constexpr’ call flows off the end of the function
   82 | constexpr std::array<uint64_t,LIMBS> the_1 = _1();
      |                                              ~~^~
skylake.hpp:83:48:   in ‘constexpr’ expansion of ‘_R()’
skylake.hpp:83:48: error: ‘constexpr’ call flows off the end of the function
   83 | constexpr std::array<uint64_t,LIMBS> the_R = _R();
      |                                              ~~^~
In file included from fp.hpp:10,
                 from params.hpp:18,
                 from main.cpp:9:
skylake.hpp: In constructor ‘_fp<__>::_fp(const string&)’:
skylake.hpp:116:26: error: no matching function for call to ‘_chop(uint_t<576>)’
  116 |             : limbs{_chop(decltype(p)(s))}
      |                     ~~~~~^~~~~~~~~~~~~~~~
In file included from fp.hpp:10,
                 from params.hpp:18,
                 from main.cpp:9:
skylake.hpp:61:38: note: candidate: ‘template<long unsigned int N> constexpr std::array<long unsigned int, 9> _chop(uint_t<N>&)’
   61 | constexpr std::array<uint64_t,LIMBS> _chop(uint_t<N> const &v)
      |                                      ^~~~~
skylake.hpp:61:38: note:   template argument deduction/substitution failed:
In file included from fp.hpp:10,
                 from params.hpp:18,
                 from main.cpp:9:
skylake.hpp:116:26: note:   mismatched types ‘long unsigned int’ and ‘unsigned int’
  116 |             : limbs{_chop(decltype(p)(s))}
      |                     ~~~~~^~~~~~~~~~~~~~~~
skylake.hpp: In constructor ‘_fp<__>::_fp(uint_t<576>&)’:
skylake.hpp:119:26: error: no matching function for call to ‘_chop(uint_t<576>&)’
  119 |             : limbs{_chop(v)}
      |                     ~~~~~^~~
In file included from fp.hpp:10,
                 from params.hpp:18,
                 from main.cpp:9:
skylake.hpp:61:38: note: candidate: ‘template<long unsigned int N> constexpr std::array<long unsigned int, 9> _chop(uint_t<N>&)’
   61 | constexpr std::array<uint64_t,LIMBS> _chop(uint_t<N> const &v)
      |                                      ^~~~~
skylake.hpp:61:38: note:   template argument deduction/substitution failed:
In file included from fp.hpp:10,
                 from params.hpp:18,
                 from main.cpp:9:
skylake.hpp:119:26: note:   mismatched types ‘long unsigned int’ and ‘unsigned int’
  119 |             : limbs{_chop(v)}
      |                     ~~~~~^~~
skylake.hpp: In member function ‘_fp<__> _fp<__>::inv() const’:
skylake.hpp:202:36: error: non-constant condition for static assertion
  202 |             static_assert(the_p[0] >= 2);
In file included from main.cpp:18:
action.hpp: In instantiation of ‘oriented_curve<F> canonicalize(oriented_curve<F>) [with EXP = _fact<p1>; L1 = _fact<L1>; L2 = _fact<L2>; L3 = _fact<L3>; F = _fq<_fp<void> >]’:
main.cpp:51:78:   required from here
action.hpp:387:27: error: ‘constexpr _fact<M, T>::num_t _fact<M, T>::value() const [with const auto& M = p1; T = unsigned char; _fact<M, T>::num_t = std::decay<const boost::multiprecision::number<boost::multiprecision::backends::cpp_int_backend<576, 576, boost::multiprecision::unsigned_magnitude, boost::multiprecision::unchecked, void>, boost::multiprecision::et_off>&>::type]’ called in a constant expression
  387 |     constexpr static auto LL12val = LL12.value();
      |                           ^~~~~~~
In file included from main.cpp:15:
fact.hpp:127:25: note: ‘constexpr _fact<M, T>::num_t _fact<M, T>::value() const [with const auto& M = p1; T = unsigned char; _fact<M, T>::num_t = std::decay<const boost::multiprecision::number<boost::multiprecision::backends::cpp_int_backend<576, 576, boost::multiprecision::unsigned_magnitude, boost::multiprecision::unchecked, void>, boost::multiprecision::et_off>&>::type]’ is not usable as a ‘constexpr’ function because:
  127 |         constexpr num_t value() const
      |                         ^~~~~
fact.hpp:132:25: error: call to non-‘constexpr’ function ‘std::vector<_Tp, _Alloc>::vector(_InputIterator, _InputIterator, const allocator_type&) [with _InputIterator = std::move_iterator<boost::multiprecision::number<boost::multiprecision::backends::cpp_int_backend<576, 576, boost::multiprecision::unsigned_magnitude, boost::multiprecision::unchecked, void>, boost::multiprecision::et_off>*>; <template-parameter-2-2> = void; _Tp = boost::multiprecision::number<boost::multiprecision::backends::cpp_int_backend<576, 576, boost::multiprecision::unsigned_magnitude, boost::multiprecision::unchecked, void>, boost::multiprecision::et_off>; _Alloc = std::allocator<boost::multiprecision::number<boost::multiprecision::backends::cpp_int_backend<576, 576, boost::multiprecision::unsigned_magnitude, boost::multiprecision::unchecked, void>, boost::multiprecision::et_off> >; std::vector<_Tp, _Alloc>::allocator_type = std::allocator<boost::multiprecision::number<boost::multiprecision::backends::cpp_int_backend<576, 576, boost::multiprecision::unsigned_magnitude, boost::multiprecision::unchecked, void>, boost::multiprecision::et_off> >]’
  132 |             std::vector t(std::make_move_iterator(qs.begin()), std::make_move_iterator(qs.end()));
      |                         ^
In file included from /usr/include/c++/11/vector:67,
                 from /usr/include/c++/11/functional:62,
                 from /usr/include/c++/11/pstl/glue_algorithm_defs.h:13,
                 from /usr/include/c++/11/algorithm:74,
                 from /usr/include/boost/iterator/iterator_concepts.hpp:26,
                 from /usr/include/boost/range/concepts.hpp:20,
                 from /usr/include/boost/range/size_type.hpp:20,
                 from /usr/include/boost/range/size.hpp:21,
                 from /usr/include/boost/range/functions.hpp:20,
                 from /usr/include/boost/range/iterator_range_core.hpp:38,
                 from /usr/include/boost/lexical_cast.hpp:30,
                 from /usr/include/boost/multiprecision/detail/number_base.hpp:20,
                 from /usr/include/boost/multiprecision/traits/is_variable_precision.hpp:10,
                 from /usr/include/boost/multiprecision/detail/precision.hpp:9,
                 from /usr/include/boost/multiprecision/number.hpp:25,
                 from /usr/include/boost/multiprecision/cpp_int.hpp:12,
                 from bigint.hpp:4,
                 from params.hpp:4,
                 from main.cpp:9:
/usr/include/c++/11/bits/stl_vector.h:653:9: note: ‘std::vector<_Tp, _Alloc>::vector(_InputIterator, _InputIterator, const allocator_type&) [with _InputIterator = std::move_iterator<boost::multiprecision::number<boost::multiprecision::backends::cpp_int_backend<576, 576, boost::multiprecision::unsigned_magnitude, boost::multiprecision::unchecked, void>, boost::multiprecision::et_off>*>; <template-parameter-2-2> = void; _Tp = boost::multiprecision::number<boost::multiprecision::backends::cpp_int_backend<576, 576, boost::multiprecision::unsigned_magnitude, boost::multiprecision::unchecked, void>, boost::multiprecision::et_off>; _Alloc = std::allocator<boost::multiprecision::number<boost::multiprecision::backends::cpp_int_backend<576, 576, boost::multiprecision::unsigned_magnitude, boost::multiprecision::unchecked, void>, boost::multiprecision::et_off> >; std::vector<_Tp, _Alloc>::allocator_type = std::allocator<boost::multiprecision::number<boost::multiprecision::backends::cpp_int_backend<576, 576, boost::multiprecision::unsigned_magnitude, boost::multiprecision::unchecked, void>, boost::multiprecision::et_off> >]’ declared here
  653 |         vector(_InputIterator __first, _InputIterator __last,
      |         ^~~~~~
In file included from main.cpp:18:
action.hpp:416:29: error: no matching function for call to ‘weil_pairing(ecp<_fq<_fp<void> > >&, ecp<_fq<_fp<void> > >&, const boost::multiprecision::number<boost::multiprecision::backends::cpp_int_backend<576, 576, boost::multiprecision::unsigned_magnitude, boost::multiprecision::unchecked, void>, boost::multiprecision::et_off>&)’
  416 |             e = weil_pairing(R, S, LL12val);
      |                 ~~~~~~~~~~~~^~~~~~~~~~~~~~~
In file included from main.cpp:12:
ecp.hpp:340:3: note: candidate: ‘template<class F, long unsigned int N> F weil_pairing(const ecp<F>&, const ecp<F>&, uint_t<N>&)’
  340 | F weil_pairing(ecp<F> const &P, ecp<F> const &Q, uint_t<N> const &n)
      |   ^~~~~~~~~~~~
ecp.hpp:340:3: note:   template argument deduction/substitution failed:
In file included from main.cpp:18:
action.hpp:416:29: note:   mismatched types ‘long unsigned int’ and ‘unsigned int’
  416 |             e = weil_pairing(R, S, LL12val);
      |                 ~~~~~~~~~~~~^~~~~~~~~~~~~~~
In file included from main.cpp:18:
action.hpp: In instantiation of ‘oriented_curve<F> scallop(const oriented_curve<F>&, const I&) [with EXP = _fact<p1>; L1 = _fact<L1>; L2 = _fact<L2>; L3 = _fact<L3>; const auto& relations = relations; I = boost::multiprecision::number<boost::multiprecision::backends::cpp_int_backend<320, 320, boost::multiprecision::unsigned_magnitude, boost::multiprecision::unchecked, void>, boost::multiprecision::et_off>; F = _fq<_fp<void> >]’:
main.cpp:68:63:   required from here
action.hpp:457:37: error: no matching function for call to ‘babai(boost::multiprecision::number<boost::multiprecision::backends::cpp_int_backend<321, 321, boost::multiprecision::signed_magnitude, boost::multiprecision::unchecked, void>, boost::multiprecision::et_off>&, const std::array<std::array<short int, 65>, 65>&, const std::array<std::array<boost::multiprecision::number<boost::multiprecision::backends::cpp_bin_float<200, boost::multiprecision::backends::digit_base_10, void, int, 0, 0>, boost::multiprecision::et_off>, 65>, 65>&)’
  457 |     exponent_vec<L1,L2,L3> v = babai(y, relations, GS);
      |                                ~~~~~^~~~~~~~~~~~~~~~~~
In file included from action.hpp:450,
                 from main.cpp:18:
babai.hpp:48:25: note: candidate: ‘template<long unsigned int N, long unsigned int B, class R> std::array<boost::multiprecision::number<boost::multiprecision::backends::cpp_int_backend<B, B, boost::multiprecision::signed_magnitude, boost::multiprecision::unchecked, void>, boost::multiprecision::expression_template_default<boost::multiprecision::backends::cpp_int_backend<B, B, boost::multiprecision::signed_magnitude, boost::multiprecision::unchecked, void> >::value>, N> babai(std::array<boost::multiprecision::number<boost::multiprecision::backends::cpp_int_backend<B, B, boost::multiprecision::signed_magnitude, boost::multiprecision::unchecked, void>, boost::multiprecision::expression_template_default<boost::multiprecision::backends::cpp_int_backend<B, B, boost::multiprecision::signed_magnitude, boost::multiprecision::unchecked, void> >::value>, N>&, matrix<short int, N, N>&, matrix<R, N, N>&)’
   48 | std::array<int_t<B>, N> babai(std::array<int_t<B>, N> &v,
      |                         ^~~~~
babai.hpp:48:25: note:   template argument deduction/substitution failed:
In file included from main.cpp:18:
action.hpp:457:37: note:   ‘boost::multiprecision::number<boost::multiprecision::backends::cpp_int_backend<321, 321, boost::multiprecision::signed_magnitude, boost::multiprecision::unchecked, void>, boost::multiprecision::et_off>’ is not derived from ‘std::array<boost::multiprecision::number<boost::multiprecision::backends::cpp_int_backend<B, B, boost::multiprecision::signed_magnitude, boost::multiprecision::unchecked, void>, boost::multiprecision::expression_template_default<boost::multiprecision::backends::cpp_int_backend<B, B, boost::multiprecision::signed_magnitude, boost::multiprecision::unchecked, void> >::value>, N>’
  457 |     exponent_vec<L1,L2,L3> v = babai(y, relations, GS);
      |                                ~~~~~^~~~~~~~~~~~~~~~~~
In file included from action.hpp:450,
                 from main.cpp:18:
babai.hpp:63:24: note: candidate: ‘template<long unsigned int N, long unsigned int B, class R> std::array<short int, N> babai(int_t<B>&, matrix<short int, N, N>&, matrix<R, N, N>&)’
   63 | std::array<int16_t, N> babai(int_t<B> const &exp,
      |                        ^~~~~
babai.hpp:63:24: note:   template argument deduction/substitution failed:
In file included from main.cpp:18:
action.hpp:457:37: note:   mismatched types ‘long unsigned int’ and ‘unsigned int’
  457 |     exponent_vec<L1,L2,L3> v = babai(y, relations, GS);
      |                                ~~~~~^~~~~~~~~~~~~~~~~~
```

Using clang++: 
```
 clang++ -std=c++20 -pedantic -Wall -Wextra -Werror -O3 -march=native -DNDEBUG *.cpp -o main -I/usr/include/c++/11 -I/usr/include/x86_64-linux-gnu/c++/11 -L /usr/lib/gcc/x86_64-linux-gnu/11
In file included from main.cpp:9:
In file included from ./params.hpp:4:
./bigint.hpp:30:15: error: missing 'typename' prior to dependent type name 'std::conditional<std::numeric_limits<I>::is_signed, int_t<2 * std::numeric_limits<I>::digits>, uint_t<2 * std::numeric_limits<I>::digits>>::type'
using dbl_t = std::conditional<
              ^~~~~~~~~~~~~~~~~
              typename 
./bigint.hpp:43:19: error: missing 'typename' prior to dependent type name 'std::conditional<std::numeric_limits<I>::is_signed, int_t<std::numeric_limits<I>::digits + 0>, int_t<std::numeric_limits<I>::digits + 1>>::type'
using signify_t = std::conditional<
                  ^~~~~~~~~~~~~~~~~
                  typename 
In file included from main.cpp:9:
In file included from ./params.hpp:18:
In file included from ./fp.hpp:10:
./skylake.hpp:72:12: error: no matching function for call to '_chop'
    return _chop(v);
           ^~~~~
./skylake.hpp:61:38: note: candidate template ignored: substitution failure: deduced non-type template argument does not have the same type as the corresponding template parameter ('unsigned int' vs 'size_t' (aka 'unsigned long'))
constexpr std::array<uint64_t,LIMBS> _chop(uint_t<N> const &v)
                                     ^
./skylake.hpp:78:12: error: no matching function for call to '_chop'
    return _chop(v);
           ^~~~~
./skylake.hpp:61:38: note: candidate template ignored: substitution failure: deduced non-type template argument does not have the same type as the corresponding template parameter ('unsigned int' vs 'size_t' (aka 'unsigned long'))
constexpr std::array<uint64_t,LIMBS> _chop(uint_t<N> const &v)
                                     ^
./skylake.hpp:81:46: error: no matching function for call to '_chop'
constexpr std::array<uint64_t,LIMBS> the_p = _chop(p);
                                             ^~~~~
./skylake.hpp:61:38: note: candidate template ignored: substitution failure: deduced non-type template argument does not have the same type as the corresponding template parameter ('unsigned int' vs 'size_t' (aka 'unsigned long'))
constexpr std::array<uint64_t,LIMBS> _chop(uint_t<N> const &v)
                                     ^
./skylake.hpp:82:46: error: call to consteval function '_1' is not a constant expression
constexpr std::array<uint64_t,LIMBS> the_1 = _1();
                                             ^
./skylake.hpp:82:38: error: constexpr variable 'the_1' must be initialized by a constant expression
constexpr std::array<uint64_t,LIMBS> the_1 = _1();
                                     ^       ~~~~
./skylake.hpp:83:46: error: call to consteval function '_R' is not a constant expression
constexpr std::array<uint64_t,LIMBS> the_R = _R();
                                             ^
./skylake.hpp:83:38: error: constexpr variable 'the_R' must be initialized by a constant expression
constexpr std::array<uint64_t,LIMBS> the_R = _R();
                                     ^       ~~~~
./skylake.hpp:116:21: error: no matching function for call to '_chop'
            : limbs{_chop(decltype(p)(s))}
                    ^~~~~
./skylake.hpp:61:38: note: candidate template ignored: substitution failure: deduced non-type template argument does not have the same type as the corresponding template parameter ('unsigned int' vs 'size_t' (aka 'unsigned long'))
constexpr std::array<uint64_t,LIMBS> _chop(uint_t<N> const &v)
                                     ^
./skylake.hpp:119:21: error: no matching function for call to '_chop'
            : limbs{_chop(v)}
                    ^~~~~
./skylake.hpp:61:38: note: candidate template ignored: substitution failure: deduced non-type template argument does not have the same type as the corresponding template parameter ('unsigned int' vs 'size_t' (aka 'unsigned long'))
constexpr std::array<uint64_t,LIMBS> _chop(uint_t<N> const &v)
                                     ^
In file included from main.cpp:9:
In file included from ./params.hpp:19:
./fq.hpp:78:32: error: cannot take address of consteval function 'cardinality' outside of an immediate invocation
            constexpr auto q = _fq::cardinality();
                               ^
./fq.hpp:22:40: note: declared here
        consteval static cardinality_t cardinality()
                                       ^
In file included from main.cpp:9:
In file included from ./params.hpp:18:
In file included from ./fp.hpp:10:
./skylake.hpp:246:30: error: constexpr variable cannot have non-literal type 'const _fp<void>'
        static constexpr _fp zero {no_montgomerize(), {0}};
                             ^
./fq.hpp:21:73: note: in instantiation of template class '_fp<void>' requested here
        using cardinality_t = dbl_t<typename std::remove_cvref<decltype(F::cardinality())>::type>;
                                                                        ^
./params.hpp:21:15: note: in instantiation of template class '_fq<_fp<void>>' requested here
fq const a4 = fq::make(0x59bff441ef2567cbe16c78901ec4c7fa2460c8ab43d5a4d715176affb7025e41a3a91996eb6ca4e830448da05c36f4922691301bcfb1e1d7ce228089c9d4bc3f2087_cppui, 0x1ab4f76d020817e2e1e82cf50107be7e81e06bbb0ecfa2f44ceb428346b9110c2800f0190be09c9ce23089b809712bdb26fba9b6eb1eb5f277e6e100a6f87c6d410b_cppui);
              ^
./skylake.hpp:246:30: note: incomplete type 'const _fp<void>' is not a literal type
        static constexpr _fp zero {no_montgomerize(), {0}};
                             ^
./skylake.hpp:106:7: note: definition of '_fp<void>' is not complete until the closing '}'
class _fp
      ^
./skylake.hpp:247:30: error: constexpr variable cannot have non-literal type 'const _fp<void>'
        static constexpr _fp one {no_montgomerize(), the_1};
                             ^
In file included from main.cpp:9:
In file included from ./params.hpp:19:
./fq.hpp:186:30: error: constexpr variable cannot have non-literal type 'const _fq<_fp<void>>'
        static constexpr _fq zero {F::zero, F::zero};
                             ^
./params.hpp:21:15: note: in instantiation of template class '_fq<_fp<void>>' requested here
fq const a4 = fq::make(0x59bff441ef2567cbe16c78901ec4c7fa2460c8ab43d5a4d715176affb7025e41a3a91996eb6ca4e830448da05c36f4922691301bcfb1e1d7ce228089c9d4bc3f2087_cppui, 0x1ab4f76d020817e2e1e82cf50107be7e81e06bbb0ecfa2f44ceb428346b9110c2800f0190be09c9ce23089b809712bdb26fba9b6eb1eb5f277e6e100a6f87c6d410b_cppui);
              ^
In file included from main.cpp:9:
In file included from ./params.hpp:19:
./fq.hpp:187:30: error: constexpr variable cannot have non-literal type 'const _fq<_fp<void>>'
        static constexpr _fq one {F::one, F::zero};
                             ^
./fq.hpp:188:30: error: constexpr variable cannot have non-literal type 'const _fq<_fp<void>>'
        static constexpr _fq gen {F::zero, F::one};
                             ^
In file included from main.cpp:15:
./fact.hpp:68:23: error: missing 'typename' prior to dependent type name 'std::decay<decltype(M)>::type'
        using num_t = std::decay<decltype(M)>::type;
                      ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~
                      typename 
In file included from main.cpp:9:
In file included from ./params.hpp:4:
In file included from ./bigint.hpp:4:
In file included from /usr/include/boost/multiprecision/cpp_int.hpp:12:
In file included from /usr/include/boost/multiprecision/number.hpp:29:
In file included from /usr/include/boost/container_hash/hash.hpp:111:
/usr/include/c++/11/optional:966:12: error: no member named '_M_is_engaged' in 'std::optional<ecp<_fq<_fp<void>>>>'
        if (this->_M_is_engaged())
            ~~~~  ^
main.cpp:29:76: note: in instantiation of member function 'std::optional<ecp<_fq<_fp<void>>>>::value' requested here
oriented_curve<fq> const _EPQ0 {E0, E0->lift_x(xP).value(), E0->lift_x(xQ).value()};
                                                                           ^
fatal error: too many errors emitted, stopping now [-ferror-limit=]
20 errors generated.
```

**Comment by meyira** [comment]
Resolved using newest versions of boost
